name: cine_flutter
description: Application catalogue de films - CineFlutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.4.0

  # State management
  provider: ^6.1.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  # Images réseau avec cache
  cached_network_image: ^3.3.0

  # Navigation
  go_router: ^12.1.0

  # URL launcher
  url_launcher: ^6.2.0

  # UI
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  animations: ^2.0.11

  # Env variables
  flutter_dotenv: ^5.1.0

  # Speech to text
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/img.png
