// Mocks generated by Mockito 5.4.4 from annotations
// in cine_flutter/test/viewmodels/search_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cine_flutter/data/models/actor.dart' as _i5;
import 'package:cine_flutter/data/models/genre.dart' as _i6;
import 'package:cine_flutter/data/models/movie.dart' as _i2;
import 'package:cine_flutter/data/models/tv_show.dart' as _i7;
import 'package:cine_flutter/data/repositories/movie_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovie_0 extends _i1.SmartFake implements _i2.Movie {
  _FakeMovie_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Movie>> getPopularMovies({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
      ) as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> getTrendingMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingMovies,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
      ) as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> getUpcomingMovies({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingMovies,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
      ) as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> searchMovies(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
          {#page: page},
        ),
        returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
      ) as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<_i2.Movie> getMovieDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.Movie>.value(_FakeMovie_0(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Movie>);

  @override
  _i4.Future<List<_i5.Actor>> getMovieCredits(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMovieCredits,
          [id],
        ),
        returnValue: _i4.Future<List<_i5.Actor>>.value(<_i5.Actor>[]),
      ) as _i4.Future<List<_i5.Actor>>);

  @override
  _i4.Future<String?> getTrailerKey(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTrailerKey,
          [id],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<List<_i2.Movie>> getSimilarMovies(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getSimilarMovies,
          [id],
        ),
        returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
      ) as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i6.Genre>> getGenres() => (super.noSuchMethod(
        Invocation.method(
          #getGenres,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Genre>>.value(<_i6.Genre>[]),
      ) as _i4.Future<List<_i6.Genre>>);

  @override
  _i4.Future<List<_i2.Movie>> getMoviesByGenre(
    int? genreId, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoviesByGenre,
          [genreId],
          {#page: page},
        ),
        returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
      ) as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i7.TvShow>> getPopularTvShows({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvShows,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<List<_i7.TvShow>>.value(<_i7.TvShow>[]),
      ) as _i4.Future<List<_i7.TvShow>>);

  @override
  _i4.Future<List<_i7.TvShow>> getTrendingTvShows() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingTvShows,
          [],
        ),
        returnValue: _i4.Future<List<_i7.TvShow>>.value(<_i7.TvShow>[]),
      ) as _i4.Future<List<_i7.TvShow>>);

  @override
  _i4.Future<List<_i7.TvShow>> searchTvShows(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvShows,
          [query],
        ),
        returnValue: _i4.Future<List<_i7.TvShow>>.value(<_i7.TvShow>[]),
      ) as _i4.Future<List<_i7.TvShow>>);

  @override
  _i4.Future<Map<String, dynamic>> searchMulti(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMulti,
          [query],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  List<_i2.Movie> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: <_i2.Movie>[],
      ) as List<_i2.Movie>);

  @override
  bool isFavorite(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [id],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> addFavorite(_i2.Movie? m) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [m],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorite(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearFavorites() => (super.noSuchMethod(
        Invocation.method(
          #clearFavorites,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
